raw_epub_dir: "./data/01-raw/"
processed_dir: "./data/02-preprocessed/"
dataset_dir: "./data/03-datasets/"
exclude_files: [
    "titlepage.xhtml",
    "toc.html",
    "game-of-thrones-00.html",
    "game-of-thrones-01.html",
    "game-of-thrones-03.html",
    "text/part0000.html",
    "text/part0001.html",
    "text/part0002.html",
    "text/part0003.html",
]
train_ratio: 0.90
val_ratio: 0.05
test_ratio: 0.05
